# Análisis de la telemetría de Timeless Deck

Limpiamos los valores y los ordenamos por su timestamp.

In [6]:
from loader import Loader
import numpy as np
import pandas as pd

# Carga de archivos

loader = Loader("TimlessDeck-15724-1745417392410329000.json", False)

dataSorted = loader.data

dataSorted = dataSorted.sort_values("timeStamp")
# Display all rows of the DataFrame

display(dataSorted)

,appName,appVersion,eType,eventId,sessionId,timeStamp,levelId,win,currentDeck,manaAfter,manaBefore,attemptedHeal,lifeAfterHeal,lifeBeforeHeal,manaCost,manaStatus
0,TimlessDeck,1.0.0,0,0,15724,2025-04-23 14:09:52.432964200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TimlessDeck,1.0.0,2,1,15724,2025-04-23 14:09:54.618975800,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TimlessDeck,1.0.0,3,2,15724,2025-04-23 14:09:57.244409000,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TimlessDeck,1.0.0,11,3,15724,2025-04-23 14:10:07.032274900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TimlessDeck,1.0.0,11,4,15724,2025-04-23 14:10:07.444096700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1083,TimlessDeck,1.0.0,7,1083,15724,2025-04-23 14:18:49.396138200,NaN,NaN,NaN,120.0,120.0,NaN,NaN,NaN,NaN,NaN
1084,TimlessDeck,1.0.0,7,1084,15724,2025-04-23 14:18:49.486052500,NaN,NaN,NaN,120.0,120.0,NaN,NaN,NaN,NaN,NaN
1085,TimlessDeck,1.0.0,7,1085,15724,2025-04-23 14:18:49.493986000,NaN,NaN,NaN,120.0,120.0,NaN,NaN,NaN,NaN,NaN
1086,TimlessDeck,1.0.0,3,1086,15724,2025-04-23 14:18:52.576561000,6.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1087,TimlessDeck,1.0.0,1,1087,15724,2025-04-23 14:19:05.860865300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Preguntas a responder
+ Determinar si la interfaz de la escena de combate transmite las mecánicas del juego.
  + ¿El jugador entiende el funcionamiento de las cartas?
  + ¿El jugador entiende las tres barras superiores?
  + ¿El jugador entiende qué tiene que hacer para salir del nivel, y cuándo lo puede hacer?

+ Determinar el grado de comprensión del inventario.
  + ¿Entiende el jugador cómo gestionar sus cartas?

## ¿El jugador entiende el funcionamiento de las cartas?

+ Cambio de carta voluntario.
  + Promedio de número de habilidades usadas por nivel.
+ Uso de habilidad.
  + Promedio de habilidades usadas con éxito (ha hecho algo de daño o ha curado), por nivel.

In [ ]:
# Coger todos los eventos de habilidades usadas y de disparos??
game_start_events = dataSorted[dataSorted["eventType"] == "GAME:START"]
game_end_events = dataSorted[dataSorted["eventType"] == "GAME:END"]

# ejemplo loop

start_timestamp_series = game_start_events.head(n=1)["timestamp"]
end_timestamp = game_end_events.head(n=1)["timestamp"]



display(type(start_timestamp_series))
display(end_timestamp)

death_events = dataSorted[dataSorted["eventType"] == "PLAYER:DEATH"]
death_events = death_events[death_events["timestamp"] >= start_timestamp.values[0]]
death_events = death_events[death_events["timestamp"] <= end_timestamp.values[0]]


test_events = dataSorted[dataSorted["timestamp"] >= start_timestamp.values[0]]
test_events = test_events[test_events["timestamp"] <= end_timestamp.values[0]]

for event in game_start_events:



display(game_start_events)
display(game_end_events)
display(death_events)
display(test_events)
display(test_events.count)
display(death_events.count())
# Separarlos por nivel
# Sacar la media

pandas.core.series.Series

131   2024-04-16 10:12:26.174
Name: timestamp, dtype: datetime64[ns]

      id   eventType               timestamp  levelId   x   y result
62     0  GAME:START 2024-04-16 10:10:12.854      NaN NaN NaN    NaN
118   35  GAME:START 2024-04-16 10:13:07.442      NaN NaN NaN    NaN
35    66  GAME:START 2024-04-16 10:15:19.493      NaN NaN NaN    NaN
1     88  GAME:START 2024-04-16 10:17:00.945      NaN NaN NaN    NaN
33   111  GAME:START 2024-04-16 10:18:59.231      NaN NaN NaN    NaN
186    0  GAME:START 2024-04-16 10:31:51.816      NaN NaN NaN    NaN
180   27  GAME:START 2024-04-16 10:33:50.650      NaN NaN NaN    NaN
183   46  GAME:START 2024-04-16 10:35:29.718      NaN NaN NaN    NaN

      id eventType               timestamp  levelId   x   y result
131   34  GAME:END 2024-04-16 10:12:26.174      NaN NaN NaN   FAIL
64    65  GAME:END 2024-04-16 10:15:14.842      NaN NaN NaN   FAIL
116   87  GAME:END 2024-04-16 10:16:59.346      NaN NaN NaN   PASS
79   110  GAME:END 2024-04-16 10:18:55.364      NaN NaN NaN   PASS
61   137  GAME:END 2024-04-16 10:21:00.199      NaN NaN NaN   FAIL
189   26  GAME:END 2024-04-16 10:33:46.634      NaN NaN NaN   PASS
191   45  GAME:END 2024-04-16 10:35:26.667      NaN NaN NaN   PASS
162   70  GAME:END 2024-04-16 10:37:29.519      NaN NaN NaN   PASS

,id,eventType,timestamp,levelId,x,y,result
120,2,PLAYER:DEATH,2024-04-16 10:10:17.055,NaN,254.928932,630.404401,NaN
40,3,PLAYER:DEATH,2024-04-16 10:10:26.171,NaN,310.897825,444.719946,NaN
90,6,PLAYER:DEATH,2024-04-16 10:10:33.939,NaN,497.759740,528.047379,NaN
122,7,PLAYER:DEATH,2024-04-16 10:10:44.172,NaN,502.169300,441.686500,NaN
108,8,PLAYER:DEATH,2024-04-16 10:10:47.121,NaN,578.136401,527.258091,NaN
124,11,PLAYER:DEATH,2024-04-16 10:10:59.705,NaN,664.426407,528.856181,NaN
80,12,PLAYER:DEATH,2024-04-16 10:11:02.972,NaN,551.023689,532.357023,NaN
93,13,PLAYER:DEATH,2024-04-16 10:11:09.906,NaN,457.257215,413.835859,NaN
28,14,PLAYER:DEATH,2024-04-16 10:11:14.072,NaN,716.714045,438.047379,NaN
59,15,PLAYER:DEATH,2024-04-16 10:11:15.455,NaN,432.000000,400.000000,NaN
12,16,PLAYER:DEATH,2024-04-16 10:11:18.189,NaN,320.619288,335.285955,NaN
113,19,PLAYER:DEATH,2024-04-16 10:11:37.256,NaN,434.323533,345.993586,NaN
65,20,PLAYER:DEATH,2024-04-16 10:11:40.039,NaN,318.927117,331.820667,NaN
47,21,PLAYER:DEATH,2024-04-16 10:11:43.089,NaN,199.406085,347.406085,NaN
30,22,PLAYER:DEATH,2024-04-16 10:11:44.139,NaN,432.000000,400.000000,NaN
15,23,PLAYER:DEATH,2024-04-16 10:11:46.439,NaN,425.333333,496.666667,NaN
128,24,PLAYER:DEATH,2024-04-16 10:11:48.589,NaN,333.952621,438.047379,NaN
115,25,PLAYER:DEATH,2024-04-16 10:11:50.622,NaN,353.715729,435.049062,NaN
98,26,PLAYER:DEATH,2024-04-16 10:12:04.474,NaN,200.522164,334.839871,NaN
85,27,PLAYER:DEATH,2024-04-16 10:12:05.539,NaN,428.666667,400.000000,NaN
49,28,PLAYER:DEATH,2024-04-16 10:12:07.856,NaN,428.666667,526.666667,NaN
31,29,PLAYER:DEATH,2024-04-16 10:12:13.140,NaN,303.785113,531.785113,NaN
52,30,PLAYER:DEATH,2024-04-16 10:12:17.757,NaN,480.521164,639.468735,NaN
34,31,PLAYER:DEATH,2024-04-16 10:12:21.407,NaN,467.732000,554.442670,NaN
19,32,PLAYER:DEATH,2024-04-16 10:12:22.208,NaN,467.732000,554.442670,NaN

,id,eventType,timestamp,levelId,x,y,result
62,0,GAME:START,2024-04-16 10:10:12.854,NaN,NaN,NaN,NaN
78,1,LEVEL:START,2024-04-16 10:10:12.915,1.0,NaN,NaN,NaN
120,2,PLAYER:DEATH,2024-04-16 10:10:17.055,NaN,254.928932,630.404401,NaN
40,3,PLAYER:DEATH,2024-04-16 10:10:26.171,NaN,310.897825,444.719946,NaN
26,4,LEVEL:END,2024-04-16 10:10:29.688,1.0,NaN,NaN,PASS
11,5,LEVEL:START,2024-04-16 10:10:29.721,2.0,NaN,NaN,NaN
90,6,PLAYER:DEATH,2024-04-16 10:10:33.939,NaN,497.759740,528.047379,NaN
122,7,PLAYER:DEATH,2024-04-16 10:10:44.172,NaN,502.169300,441.686500,NaN
108,8,PLAYER:DEATH,2024-04-16 10:10:47.121,NaN,578.136401,527.258091,NaN
91,9,LEVEL:END,2024-04-16 10:10:54.455,2.0,NaN,NaN,PASS
112,10,LEVEL:START,2024-04-16 10:10:54.493,3.0,NaN,NaN,NaN
124,11,PLAYER:DEATH,2024-04-16 10:10:59.705,NaN,664.426407,528.856181,NaN
80,12,PLAYER:DEATH,2024-04-16 10:11:02.972,NaN,551.023689,532.357023,NaN
93,13,PLAYER:DEATH,2024-04-16 10:11:09.906,NaN,457.257215,413.835859,NaN
28,14,PLAYER:DEATH,2024-04-16 10:11:14.072,NaN,716.714045,438.047379,NaN
59,15,PLAYER:DEATH,2024-04-16 10:11:15.455,NaN,432.000000,400.000000,NaN
12,16,PLAYER:DEATH,2024-04-16 10:11:18.189,NaN,320.619288,335.285955,NaN
27,17,LEVEL:END,2024-04-16 10:11:28.705,3.0,NaN,NaN,PASS
94,18,LEVEL:START,2024-04-16 10:11:28.732,4.0,NaN,NaN,NaN
113,19,PLAYER:DEATH,2024-04-16 10:11:37.256,NaN,434.323533,345.993586,NaN
65,20,PLAYER:DEATH,2024-04-16 10:11:40.039,NaN,318.927117,331.820667,NaN
47,21,PLAYER:DEATH,2024-04-16 10:11:43.089,NaN,199.406085,347.406085,NaN
30,22,PLAYER:DEATH,2024-04-16 10:11:44.139,NaN,432.000000,400.000000,NaN
15,23,PLAYER:DEATH,2024-04-16 10:11:46.439,NaN,425.333333,496.666667,NaN
128,24,PLAYER:DEATH,2024-04-16 10:11:48.589,NaN,333.952621,438.047379,NaN
115,25,PLAYER:DEATH,2024-04-16 10:11:50.622,NaN,353.715729,435.049062,NaN
98,26,PLAYER:DEATH,2024-04-16 10:12:04.474,NaN,200.522164,334.839871,NaN
85,27,PLAYER:DEATH,2024-04-16 10:12:05.539,NaN,428.666667,400.000000,NaN
49,28,PLAYER:DEATH,2024-04-16 10:12:07.856,NaN,428.666667,526.666667,NaN
31,29,PLAYER:DEATH,2024-04-16 10:12:13.140,NaN,303.785113,531.785113,NaN
52,30,PLAYER:DEATH,2024-04-16 10:12:17.757,NaN,480.521164,639.468735,NaN
34,31,PLAYER:DEATH,2024-04-16 10:12:21.407,NaN,467.732000,554.442670,NaN
19,32,PLAYER:DEATH,2024-04-16 10:12:22.208,NaN,467.732000,554.442670,NaN
3,33,LEVEL:END,2024-04-16 10:12:23.724,4.0,NaN,NaN,FAIL
131,34,GAME:END,2024-04-16 10:12:26.174,NaN,NaN,NaN,FAIL

id           35
eventType    35
timestamp    35
levelId       8
x            25
y            25
result        5
dtype: int64

id           25
eventType    25
timestamp    25
levelId       0
x            25
y            25
result        0
dtype: int64

## ¿El jugador entiende las tres barras superiores?

+ Promedio de vida curada con el máximo de salud por nivel.
  + Curación jugador.
  + Cantidad de vida.
+ Promedio de veces que se intenta lanzar una habilidad sin maná por nivel.
  + Mana insuficiente.
+ Promedio de maná útil que se recoge por nivel.
  + Recoger maná.

## ¿El jugador entiende qué tiene que hacer para salir del nivel, y cuándo lo puede hacer?
+ Promedio de tiempo que tarda desde que puede salir del nivel hasta que sale.
  + Se puede salir del nivel.
  + Salir del nivel.
+ Promedio de veces que se intenta salir del nivel sin poder por nivel.
  + Se intenta salir del nivel.

## ¿Entiende el jugador cómo gestionar sus cartas?
+ Promedio de veces que se cambia de cartas entre mazo y mano por sesión de juego.
    + Mover una carta del mazo a la mano.
+ Promedio de veces que se cambia de cartas entre mano y mazo por sesión de juego.
    + Mover una carta de la mano al mazo.
+ Promedio de cambios de baraja final por sesión de juego.
    + Baraja actual (muestra la baraja en un momento dado, permite la posterior comparación entre barajas).